# Generated by Django 5.2.7 on 2025-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('address_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('address_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('address_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone_number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
            },
        ),
    ]
