# Generated by Django 5.2.7 on 2025-10-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='CategoryModel/%Y/%m/%d', verbose_name='image')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('author_en', models.CharField(max_length=100, null=True, verbose_name='author')),
                ('author_ru', models.CharField(max_length=100, null=True, verbose_name='author')),
                ('author_uz', models.CharField(max_length=100, null=True, verbose_name='author')),
                ('sub_title', models.CharField(max_length=400, verbose_name='sub title')),
                ('sub_title_en', models.CharField(max_length=400, null=True, verbose_name='sub title')),
                ('sub_title_ru', models.CharField(max_length=400, null=True, verbose_name='sub title')),
                ('sub_title_uz', models.CharField(max_length=400, null=True, verbose_name='sub title')),
                ('second_title', models.CharField(blank=True, max_length=100, verbose_name='second_title')),
                ('second_title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='second_title')),
                ('second_title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='second_title')),
                ('second_title_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='second_title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='text')),
                ('text_uz', models.TextField(blank=True, null=True, verbose_name='text')),
                ('featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('special', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tag')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='tag')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='tag')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Category.categorymodel', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='Category.tag', verbose_name='tag'),
        ),
    ]
