# Generated by Django 5.2.6 on 2025-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='sub_title',
            field=models.CharField(max_length=400, verbose_name='sub title'),
        ),
    ]
