# Generated by Django 5.2.6 on 2025-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_categorymodel_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
