# Generated by Django 5.2.6 on 2025-10-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_categorymodel_featured_categorymodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
