# Generated by Django 5.2.7 on 2025-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About/Aboutmodel/%Y/%m/%d', verbose_name='image')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('sub_title', models.CharField(max_length=250, verbose_name='sub title')),
                ('sub_title_en', models.CharField(max_length=250, null=True, verbose_name='sub title')),
                ('sub_title_ru', models.CharField(max_length=250, null=True, verbose_name='sub title')),
                ('sub_title_uz', models.CharField(max_length=250, null=True, verbose_name='sub title')),
                ('function1', models.CharField(max_length=150, verbose_name='function1')),
                ('function1_en', models.CharField(max_length=150, null=True, verbose_name='function1')),
                ('function1_ru', models.CharField(max_length=150, null=True, verbose_name='function1')),
                ('function1_uz', models.CharField(max_length=150, null=True, verbose_name='function1')),
                ('function2', models.CharField(blank=True, max_length=150, null=True, verbose_name='function2')),
                ('function2_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='function2')),
                ('function2_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='function2')),
                ('function2_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='function2')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About/Team/%Y/%m/%d', verbose_name='image')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='position')),
                ('position_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='position')),
                ('position_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='position')),
                ('position_uz', models.CharField(blank=True, max_length=50, null=True, verbose_name='position')),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='sub title')),
                ('sub_title_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='sub title')),
                ('sub_title_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='sub title')),
                ('sub_title_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='sub title')),
                ('x_link', models.URLField(blank=True, null=True, verbose_name='x link')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='facebook link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='instagram link')),
                ('Linkedin_link', models.URLField(blank=True, null=True, verbose_name='Linkedin link')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
